branch-defaults:
  master:
    environment: prevalencemap-prod
  sf-deployment:
    environment: prevalencemap-staging
environment-defaults:
  prevalencemap-staging:
    branch: null
    repository: null
global:
  application_name: spectrumnews.org
  default_ec2_keyname: ansible at rack
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/64bit Amazon Linux 2 v3.3.5 running Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
